### PR TITLE
deploy: warn user if `deployment.toml`'s  `[lock]  is not well known

### LINKED ISSUE #647: Subcommand `deploy gen-txs` doesn't check validation of code_hash/hash_type of lock section
Use the command lines below:
```
ckb-cli deploy gen-txs
```

When the code_hash/hash_type in lock section in `deployment.toml` is incorrect, it doesn't warn users. e.g

```
[lock]
code_hash = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
args = "0x00000000000000000000000000"
hash_type = "data1"
```
It should warn users that the code_hash/hash_type doesn't belongs to known scripts.

### PR DESCRIPTION
**Pull request by eval-exec**
Fix https://github.com/nervosnetwork/ckb-cli/issues/647

Request for review: @XuJiandong @quake @zhangsoledad @driftluo @sunchengzhu

### CODE REVIEW

File: src/subcommands/deploy/mod.rs [hunk 1]
```diff
@@ -596,6 +600,34 @@ fn load_deployment(file_path: &Path) -> Result<Deployment> {
...
 
+fn validate_lock_script(lock_script: &packed::Script) {
+    let code_hash: H256 = lock_script.code_hash().unpack();
+    let hash_type: ScriptHashType = lock_script
+        .hash_type()
+        .try_into()
+        .unwrap_or(ScriptHashType::Data);
+
+    // Check if it matches known system scripts
+    let is_known =
```
Comment (XuJiandong) [inline src/subcommands/deploy/mod.rs:611]: zero lock is also a well known script.

Comment (eval-exec) [reply src/subcommands/deploy/mod.rs:611]: fixed

**Review by XuJiandong — APPROVED** [review]

**Review by zhangsoledad — APPROVED** [review]
