### PR TITLE
fix: Default sync index db to tip

### LINKED ISSUE #281: The command line mode has no warning message about the out-dated index
<details><summary>Chat log from Telegram</summary>

<pre><code>Kenny Bambridge, [May 18, 2020 at 7:40:51 AM]:
ckb-cli wallet get-capacity --address ckt1**wgna
total: 0.0 (CKB)

thats what it outputs

but thats what it shows in ckb studio

Matt Quinn, [May 18, 2020 at 7:41:40 AM]:
does the balance for the other address come back correct?

Kenny Bambridge, [May 18, 2020 at 7:41:45 AM]:
no

ckb-cli just doesn't seem to output it correctly

Matt Quinn, [May 18, 2020 at 7:42:06 AM]:
can you check if the block fields are matching up?

like latest block?

Kenny Bambridge, [May 18, 2020 at 7:48:25 AM]:
yep they match closely

20978

20984

it just updates every 5s

Kenny Bambridge, [May 18, 2020 at 7:50:16 AM]:
so I can see the two transactions from ckb-cli: ckb-cli 
rpc get_transactions_by_lock_hash --hash 0x2b0f**366419 --page 0
- created_by:
    block_number: 20593
    tx_hash: 0x5930e**13516c
    index: 0
  consumed_by: ~
- created_by:
    block_number: 20659
    tx_hash: 0x3f833**4c08
    index: 0
  consumed_by: ~

I sent two transactions with 20000 ckb

transaction:
  version: 0
  cell_deps:
    - out_point:
        tx_hash: 0xace5**13058555b708
        index: 0
      dep_type: dep_group
  header_deps: []
  inputs:
    ...
  outputs:
    - capacity: "20090.0"
      lock:
        code_hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 (sighash)
        args: 0x2fa3c***b7249
        hash_type: type
      type: ~
  outputs_data:
    - 0x
  witnesses:
    ...
  hash: 0x3f833d***2f7464c08
tx_status:
  status: committed
  block_hash: 0x41fd***e1e3aa03cd4

Kenny Bambridge, [May 18, 2020 at 7:53:36 AM]:
^ proof that it actually sent 20009 ckb

I think something is wrong with the get-capacity function in ckb-cli

Kenny Bambridge, [May 18, 2020 at 8:03:55 AM]:
Okay @MattQuinn I found the issue...

I didn't run ckb-cli server

the command should probably warn you if that's not running

all it does is report 0 CKB LOL

ian, [May 18, 2020 at 8:16:30 AM]:
I think that's not the reason. CKb-cli will synchronize data from the node and build its own index. The command line option --wait-for-sync tells ckb-cli to block until the index is up-to-dated. Ckb-cli needs to run in the background to build the index, the interactive mode and ckb-cli server will do the trick. I believe in the interactive mode, ckb-cli does throw warning when the index is not ready yet, it seems that such warning is absent in command line mode.</code></pre>

</details>

### LINKED ISSUE #292: Should the `--wait-for-sync` option be enabled defaultly?
Suggestion:

* Make `wait-for-sync` default enabled.
* Provides a negative option `--no-sync` to disable `wait-for-sync`.

Reasons:

* User expect the correct result, but without the option, ckb-cli often returns the unexpected result, which confuses users.
* Mostly subcommand depend on the `index` state, which often can't work properly if `index` is lack of syncing.
* We should make the program safe and usable default.

### PR DESCRIPTION
**Pull request by TheWaWaR**
BREAKING CHANGE:  Now default sync index db to tip

fix #292
fix #281

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -289,8 +282,8 @@ pub fn build_cli<'a>(version_short: &'a str, version_long: &'a str) -> App<'a> {
                 .about("Display request parameters"),
         )
         .arg(
-            Arg::with_name("wait-for-sync")
-                .long("wait-for-sync")
+            Arg::with_name("no-sync")
+                .long("no-sync")
                 .global(true)
                 .about(
                     "Ensure the index-store synchronizes completely before command being executed",
```
Comment (jjyr) [inline src/main.rs:289]: The description is out of date.
