### PR TITLE
fix: jsonrpc-client thread leak

### LINKED ISSUE #47: ckb-cli open too many threads
IMAGE 2019-08-15 01:32:13

Number of threads jumps crazy after the two steps.

1. Open the interactive mode and leave.
2. shutdown the ckb node.

Seems like the index threads hangs.

### PR DESCRIPTION
**Pull request by TheWaWaR**
fix #47

### CODE REVIEW

File: src/subcommands/wallet/index.rs [hunk 1]
```diff
@@ -238,16 +249,20 @@ pub fn start_index_thread(
 fn process(
     receiver: &Receiver<Request<IndexRequest, IndexResponse>>,
     rpc_url: &mut String,
+    rpc_client: &mut HttpRpcClient,
     index_dir: &PathBuf,
     state: &Arc<RwLock<IndexThreadState>>,
     shutdown: &Arc<AtomicBool>,
 ) -> Result<bool, String> {
+    let old_rpc_url = rpc_url.clone();
     if let Some(exit) = try_recv(&receiver, rpc_url) {
```
Comment (doitian) [inline src/subcommands/wallet/index.rs]: Why the `recv` method will modify the URL?

Comment (doitian) [reply src/subcommands/wallet/index.rs]: It should be named `try_process` to avoid misunderstanding.

Comment (TheWaWaR) [reply src/subcommands/wallet/index.rs]: Maybe confused with `process` function?
